# deploy_task.ps1
# Deploy Obsybox system monitoring as a scheduled task under current user account

param(
    [string]$PythonPath = "",
    [string]$UserAccount = $env:USERNAME,
    [switch]$Force
)

Write-Host "🏗️ Obsybox System Monitoring Task Deployment" -ForegroundColor Cyan
Write-Host "=============================================" -ForegroundColor Cyan

# Check if running as administrator
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")
if (-not $isAdmin) {
    Write-Host "⚠️ This script requires Administrator privileges" -ForegroundColor Red
    Write-Host "   Please run PowerShell as Administrator and try again" -ForegroundColor Yellow
    exit 1
}

# Set up paths
$repoPath = "C:\Users\$UserAccount\Documents\obsybox"
$scriptPath = "$repoPath\systemMonitoring\ComputeMonitoring\get_system_stats.py"
$wrapperPath = "$repoPath\systemMonitoring\ComputeMonitoring\run_get_system_stats.cmd"
$logDir = "C:\Logs\obsybox"
$logFile = "$logDir\get_system_stats.log"
$taskName = "Obsybox_GetSystemStats"

# Detect Python if not provided
if ([string]::IsNullOrEmpty($PythonPath)) {
    Write-Host "🔍 Auto-detecting Python installation..." -ForegroundColor Yellow
    
    # Try common Python paths
    $pythonCandidates = @(
        "C:\Users\$UserAccount\AppData\Local\Microsoft\WindowsApps\python.exe",
        "C:\Users\$UserAccount\AppData\Local\Programs\Python\Python313\python.exe",
        "C:\Users\$UserAccount\AppData\Local\Programs\Python\Python312\python.exe",
        "C:\Users\$UserAccount\AppData\Local\Programs\Python\Python311\python.exe",
        "C:\Python313\python.exe",
        "C:\Python312\python.exe",
        "C:\Python311\python.exe"
    )
    
    foreach ($candidate in $pythonCandidates) {
        if (Test-Path $candidate) {
            $PythonPath = $candidate
            Write-Host "✅ Found Python: $PythonPath" -ForegroundColor Green
            break
        }
    }
    
    if ([string]::IsNullOrEmpty($PythonPath)) {
        Write-Host "❌ Could not auto-detect Python installation" -ForegroundColor Red
        Write-Host "   Please provide -PythonPath parameter" -ForegroundColor Yellow
        exit 1
    }
}

# Verify paths exist
if (-not (Test-Path $scriptPath)) {
    Write-Host "❌ Script not found: $scriptPath" -ForegroundColor Red
    exit 1
}

if (-not (Test-Path $PythonPath)) {
    Write-Host "❌ Python not found: $PythonPath" -ForegroundColor Red
    exit 1
}

Write-Host "📋 Configuration:" -ForegroundColor White
Write-Host "   User Account: $UserAccount" -ForegroundColor Gray
Write-Host "   Python Path: $PythonPath" -ForegroundColor Gray
Write-Host "   Script Path: $scriptPath" -ForegroundColor Gray
Write-Host "   Log File: $logFile" -ForegroundColor Gray

# Create log directory
if (-not (Test-Path $logDir)) {
    Write-Host "📁 Creating log directory: $logDir" -ForegroundColor Yellow
    New-Item -Path $logDir -ItemType Directory -Force | Out-Null
}

# Create/update wrapper script
Write-Host "📝 Creating wrapper script..." -ForegroundColor Yellow
$wrapperContent = @"
@echo off
REM Obsybox System Monitoring Wrapper
REM Generated by deploy_task.ps1

"$PythonPath" "$scriptPath" >> "$logFile" 2>&1
"@

Set-Content -Path $wrapperPath -Value $wrapperContent -Encoding ASCII
Write-Host "✅ Wrapper created: $wrapperPath" -ForegroundColor Green

# Remove existing task if it exists
try {
    $existingTask = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
    if ($existingTask) {
        if ($Force) {
            Write-Host "🗑️ Removing existing task..." -ForegroundColor Yellow
            Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
        } else {
            Write-Host "⚠️ Task '$taskName' already exists" -ForegroundColor Yellow
            Write-Host "   Use -Force to overwrite" -ForegroundColor Gray
            exit 1
        }
    }
} catch {
    # Task doesn't exist, continue
}

# Create scheduled task
Write-Host "⏰ Creating scheduled task..." -ForegroundColor Yellow

# Task action
$action = New-ScheduledTaskAction -Execute $wrapperPath

# Task trigger (every minute)
$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Minutes 1) -RepetitionDuration (New-TimeSpan -Days 365)

# Task settings
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RunOnlyIfNetworkAvailable:$false

# Task principal (run as current user when logged on)
$principal = New-ScheduledTaskPrincipal -UserId $UserAccount -LogonType Interactive -RunLevel Highest

# Register the task
Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Description "Obsybox system monitoring - publishes system stats to MQTT"

Write-Host "✅ Task '$taskName' created successfully!" -ForegroundColor Green

# Test the task
Write-Host "🧪 Testing task execution..." -ForegroundColor Yellow
Start-ScheduledTask -TaskName $taskName

Start-Sleep 3

# Check if log file was created/updated
if (Test-Path $logFile) {
    $logContent = Get-Content $logFile -Tail 5 -ErrorAction SilentlyContinue
    if ($logContent) {
        Write-Host "✅ Task executed successfully! Recent log entries:" -ForegroundColor Green
        $logContent | ForEach-Object { Write-Host "   $_" -ForegroundColor Gray }
    } else {
        Write-Host "⚠️ Log file exists but appears empty" -ForegroundColor Yellow
    }
} else {
    Write-Host "⚠️ Log file not created yet - task may still be starting" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "🎉 Deployment Complete!" -ForegroundColor Green
Write-Host "   Task Name: $taskName" -ForegroundColor White
Write-Host "   Runs every: 1 minute" -ForegroundColor White
Write-Host "   User Account: $UserAccount" -ForegroundColor White
Write-Host "   Log File: $logFile" -ForegroundColor White
Write-Host ""
Write-Host "📊 Monitor logs with:" -ForegroundColor Cyan
Write-Host "   Get-Content '$logFile' -Tail 10 -Wait" -ForegroundColor Gray
Write-Host ""
Write-Host "🔧 Manage task with:" -ForegroundColor Cyan
Write-Host "   Start-ScheduledTask -TaskName '$taskName'" -ForegroundColor Gray
Write-Host "   Stop-ScheduledTask -TaskName '$taskName'" -ForegroundColor Gray
Write-Host "   Get-ScheduledTask -TaskName '$taskName'" -ForegroundColor Gray