#!/usr/bin/env python3
"""Simulate observations against NINA (using simulators if configured).

This script will:
- Query NINA for connected equipment (camera/mount/dome/filterwheel)
- Build a tiny sequence for three targets
- Attempt to upload and optionally start the sequence via the NINA API

Notes / assumptions:
- Assumes NINA is reachable at http://localhost:1888 (change NINA_API_URL)
- If API endpoints for sequence upload/start are not available, the script will
  save a sequence JSON file you can import into NINA manually.
- Default mode is safe: it won't force real mount movement unless you pass
  --start to request sequence start (and even that depends on the NINA server)

Usage examples:
    python nina_simulate_observations.py --dry-run
    python nina_simulate_observations.py         # attempts upload but won't start by default
    python nina_simulate_observations.py --start

"""

import argparse
import json
import time
from datetime import datetime
import os
import sys

import requests

NINA_API_URL = "http://localhost:1888"
EQUIPMENT_ENDPOINTS = {
    "camera": "/v2/api/equipment/camera/info",
    "mount": "/v2/api/equipment/mount/info",
    "dome": "/v2/api/equipment/dome/info",
    "filterwheel": "/v2/api/equipment/filterwheel/info",
}

SEQUENCE_SAVE_DIR = os.path.join(os.path.dirname(__file__), "nina_generated_sequences")


def get_timestamp():
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def query(endpoint):
    try:
        r = requests.get(f"{NINA_API_URL}{endpoint}", timeout=5)
        r.raise_for_status()
        return r.json()
    except requests.RequestException as e:
        print(f"[!] API request to {endpoint} failed: {e}")
        return None


def detect_equipment():
    print("Detecting equipment via NINA API...")
    info = {}
    for key, endpoint in EQUIPMENT_ENDPOINTS.items():
        data = query(endpoint)
        if data and isinstance(data, dict):
            resp = data.get("Response", {})
            info[key] = {
                "connected": resp.get("Connected", False),
                "name": resp.get("Name", "Unknown"),
                "raw": resp,
            }
        else:
            info[key] = {"connected": False, "name": None, "raw": None}

    for k, v in info.items():
        print(f"  - {k}: {'connected' if v['connected'] else 'not connected'} ({v['name']})")

    return info


def build_sequence(targets, camera_name=None, exposure_seconds=5):
    """Build a minimal NINA-like sequence JSON structure for targets.

    This is a conservative structure intended for manual import if the upload
    endpoints are different on the user's NINA version. It contains one task
    per target: slew (simulated) + exposure.
    """
    seq = {
        "Name": f"obsybox_sim_{get_timestamp()}",
        "Description": "Simulated sequence generated by obsybox",
        "Created": datetime.utcnow().isoformat() + "Z",
        "Steps": [],
    }

    for t in targets:
        step = {
            "Name": f"Obs {t['name']}",
            "SlewTo": {"RA": t["ra"], "Dec": t["dec"]},
            "Image": {
                "Camera": camera_name or "",
                "Exposure": exposure_seconds,
                "Count": 1,
            },
        }
        seq["Steps"].append(step)

    return seq


def try_upload_sequence(sequence_json):
    """Attempt to upload the sequence to a likely NINA endpoint.

    NINA's API versions differ; try a reasonable endpoint and return the response
    or None.
    """
    # endpoints and common import variations
    endpoints_to_try = [
        "/v2/api/sequence",
        "/v2/api/sequence/load",
        "/v2/api/sequence/save",
        "/v2/api/sequence/import",
        "/v2/api/sequences/load",
        "/v2/api/sequences/import",
    ]

    # Also try simple wrapper variations if raw upload fails
    wrappers = [
        (None, sequence_json),
        ("Sequence", {"Sequence": sequence_json}),
        ("Container", {"Container": sequence_json}),
        ("Value", {"Value": sequence_json}),
        ("Data", {"Data": sequence_json}),
    ]

    for ep in endpoints_to_try:
        url = f"{NINA_API_URL}{ep}"
        for wrap_name, payload in wrappers:
            try:
                label = f"{ep}{' ('+wrap_name+')' if wrap_name else ''}"
                print(f"Attempting POST {url} {('(wrapped as '+wrap_name+')') if wrap_name else ''} ...")
                r = requests.post(url, json=payload, timeout=15)
                # log basic response
                print(f"  -> {ep} returned status {r.status_code}")
                try:
                    jr = r.json()
                    print(f"     Response JSON keys: {list(jr.keys())}")
                except Exception:
                    jr = None
                if r.status_code in (200, 201):
                    print(f"  -> Uploaded to {ep} (status {r.status_code})")
                    return jr or {"status_code": r.status_code, "text": r.text}
                else:
                    # helpful debug when server returns an error object in body
                    if jr and isinstance(jr, dict):
                        print(f"     Server response: {json.dumps(jr, indent=2)[:800]}")
                    else:
                        print(f"     Body preview: {r.text[:400]!r}")
            except requests.RequestException as e:
                print(f"  -> POST to {ep} failed: {e}")

    return None


def try_upload_sequence_file(file_path):
    """Attempt to upload a sequence file (multipart/form-data) to NINA.

    Some NINA versions expect a file upload (the UI uses a file import), so try
    posting the JSON file as form-data to common import endpoints.
    """
    # The NINA docs indicate POST /sequence/load expects raw JSON in the request body.
    endpoints_to_try = [
        "/v2/api/sequence/load",
        "/v2/api/sequence/import",
        "/v2/api/sequences/import",
        "/v2/api/sequence",
    ]

    try:
        with open(file_path, "r", encoding="utf-8") as fh:
            raw = fh.read()
    except FileNotFoundError:
        print(f"[!] Sequence file not found: {file_path}")
        return None

    headers = {"Content-Type": "application/json"}
    for ep in endpoints_to_try:
        url = f"{NINA_API_URL}{ep}"
        try:
            print(f"Attempting raw JSON POST to {url} ...")
            r = requests.post(url, data=raw.encode('utf-8'), headers=headers, timeout=20)
            print(f"  -> {ep} returned status {r.status_code}")
            try:
                jr = r.json()
                print(f"     Response JSON keys: {list(jr.keys())}")
            except Exception:
                jr = None
            if r.status_code in (200, 201):
                print(f"  -> Uploaded raw JSON to {ep} (status {r.status_code})")
                return jr or {"status_code": r.status_code, "text": r.text}
            else:
                if jr and isinstance(jr, dict):
                    print(f"     Server response: {json.dumps(jr, indent=2)[:800]}")
                else:
                    print(f"     Body preview: {r.text[:400]!r}")
        except requests.RequestException as e:
            print(f"  -> POST to {ep} failed: {e}")

    return None


def try_start_sequence(sequence_name_or_id):
    """Attempt to start a sequence by name or id. This depends on NINA version.

    Try a couple of endpoints; if none work, return False.
    """
    endpoints = [
        ("/v2/api/sequence/run", {"SequenceName": sequence_name_or_id}),
        ("/v2/api/sequence/start", {"SequenceName": sequence_name_or_id}),
    ]

    # Newer docs show Sequence Start is a GET to /v2/api/sequence/start
    for ep, payload in endpoints:
        url = f"{NINA_API_URL}{ep}"
        try:
            print(f"Attempting to start sequence via {url} (GET) ...")
            r = requests.get(url, timeout=10)
            if r.status_code == 200:
                print("  -> Sequence start request accepted")
                return True
            else:
                print(f"  -> {ep} returned {r.status_code}: {r.text}")
        except requests.RequestException as e:
            print(f"  -> GET to {ep} failed: {e}")

    return False


def try_start_sequence_more(sequence_name_or_id):
    """Try a broader set of endpoints/payloads to start a sequence.

    This function will attempt several plausible endpoints and HTTP methods
    and will return True if any indicate success.
    """
    tried = []

    # Candidate endpoints with method and payload factory
    candidates = [
        ("POST", "/v2/api/sequence/run", lambda v: {"SequenceName": v}),
        ("POST", "/v2/api/sequence/start", lambda v: {"SequenceName": v}),
        ("POST", "/v2/api/sequence/execute", lambda v: {"SequenceName": v}),
        ("POST", "/v2/api/sequences/run", lambda v: {"SequenceName": v}),
        ("POST", "/v2/api/sequences/start", lambda v: {"SequenceName": v}),
        ("POST", "/v2/api/sequence/startbyname", lambda v: {"Name": v}),
        ("GET", "/v2/api/sequence/run", lambda v: None),
    ]

    for method, ep, payload_fn in candidates:
        url = f"{NINA_API_URL}{ep}"
        try:
            print(f"Trying {method} {url} ...")
            if method == "POST":
                payload = payload_fn(sequence_name_or_id)
                r = requests.post(url, json=payload, timeout=10)
            else:
                r = requests.get(url, timeout=10)

            tried.append((ep, r.status_code, r.text[:200]))
            if r.status_code == 200:
                print(f"  -> {ep} returned 200 OK; response preview: {r.text[:200]!r}")
                return True
            else:
                print(f"  -> {ep} returned {r.status_code}: {r.text[:200]!r}")
        except requests.RequestException as e:
            print(f"  -> {ep} request failed: {e}")

    # If none succeeded, attempt to discover uploaded sequences via list endpoints
    list_eps = [
        "/v2/api/sequence/list",
        "/v2/api/sequences",
        "/v2/api/sequence",
        "/v2/api/sequence/listall",
    ]
    for ep in list_eps:
        url = f"{NINA_API_URL}{ep}"
        try:
            print(f"Querying possible sequence list endpoint {url} ...")
            r = requests.get(url, timeout=10)
            print(f"  -> {ep} returned {r.status_code}; preview: {r.text[:400]!r}")
            if r.status_code == 200:
                # crude search for our sequence name
                if sequence_name_or_id in r.text:
                    print(f"Found sequence '{sequence_name_or_id}' in {ep}; you can start it from the UI")
                    return False
        except requests.RequestException as e:
            print(f"  -> GET {ep} failed: {e}")

    print("No start endpoint succeeded and sequence listing endpoints did not reveal the uploaded sequence.")
    return False


def save_sequence_to_file(sequence_json):
    os.makedirs(SEQUENCE_SAVE_DIR, exist_ok=True)
    fname = os.path.join(SEQUENCE_SAVE_DIR, f"sequence_{get_timestamp()}.json")
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(sequence_json, f, indent=2)
    print(f"Saved sequence JSON to {fname}")
    return fname


def main(argv=None):
    p = argparse.ArgumentParser(description="Simulate observations using NINA simulators")
    p.add_argument("--dry-run", action="store_true", help="Don't attempt to upload; just build and save the sequence")
    p.add_argument("--start", action="store_true", help="If upload successful, attempt to start the sequence")
    p.add_argument("--sequence-file", "-f", help="Path to an existing NINA sequence JSON to upload (overrides built sequence)")
    p.add_argument("--exposure", type=float, default=5.0, help="Exposure time in seconds for each target")
    args = p.parse_args(argv)
    equipment = detect_equipment()
    camera_name = equipment.get("camera", {}).get("name") or ""

    # If a sequence file is provided, load it and use that as the payload.
    seq = None
    if args.sequence_file:
        seq_path = os.path.expanduser(args.sequence_file)
        if not os.path.isabs(seq_path):
            seq_path = os.path.join(os.getcwd(), seq_path)
        try:
            with open(seq_path, "r", encoding="utf-8") as f:
                seq = json.load(f)
            print(f"Loaded sequence JSON from {seq_path}")
        except Exception as e:
            print(f"[!] Failed to load sequence file {seq_path}: {e}")
            return 3

    # Otherwise build a simple sequence programmatically
    if seq is None:
        targets = [
            {"name": "M42 Orion Nebula", "ra": "05:35:17", "dec": "-05:23:14"},
            {"name": "M31 Andromeda Galaxy", "ra": "00:42:44", "dec": "+41:16:09"},
            {"name": "M13 Hercules Cluster", "ra": "16:41:41", "dec": "+36:27:37"},
        ]

        seq = build_sequence(targets, camera_name=camera_name, exposure_seconds=args.exposure)
        print("Built sequence payload (short preview):")
        print(json.dumps({"Name": seq.get("Name"), "Steps": [{"Name": s.get("Name")} for s in seq.get("Steps", [])]}, indent=2))

    if args.dry_run:
        print("Dry run: saving sequence to file and exiting.")
        save_sequence_to_file(seq)
        return 0

    upload_result = None
    # If sequence originated from a file, try file upload first (matches UI behavior)
    if args.sequence_file:
        upload_result = try_upload_sequence_file(seq_path)
    # Fallback to JSON-based upload
    if not upload_result:
        upload_result = try_upload_sequence(seq)
    if not upload_result:
        print("Upload attempts failed; saving sequence to file for manual import.")
        save_sequence_to_file(seq)
        return 2

    print("Upload returned:", upload_result)

    if args.start:
        # Try to extract an identifier or name from upload_result
        seq_identifier = None
        if isinstance(upload_result, dict):
            # server-specific fields that might contain an identifier
            seq_identifier = upload_result.get("Name") or upload_result.get("Id") or upload_result.get("Response")
        if not seq_identifier and isinstance(seq, dict):
            seq_identifier = seq.get("Name")

        started = False
        if seq_identifier:
            print(f"Attempting to start sequence using identifier/name: {seq_identifier}")
            started = try_start_sequence(seq_identifier)

        if not started:
            print("Original start attempts failed; trying broader start/discovery methods...")
            started = try_start_sequence_more(seq_identifier or (seq.get("Name") if isinstance(seq, dict) else ""))

        if started:
            print("Sequence start requested successfully.")
        else:
            print("Could not programmatically start sequence. You can start it from the NINA UI or check server logs for upload errors.")

    print("Done. If NINA is configured with simulators, check the UI/logs to confirm simulated images were produced.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
